# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/tkroeger/phd/src/mmwc/damascene

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/tkroeger/phd/src/mmwc/damascene

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tkroeger/phd/src/mmwc/damascene/CMakeFiles /home/tkroeger/phd/src/mmwc/damascene/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tkroeger/phd/src/mmwc/damascene/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named damascene

# Build rule for target.
damascene: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 damascene
.PHONY : damascene

# fast build rule for target.
damascene/fast:
	$(MAKE) -f CMakeFiles/damascene.dir/build.make CMakeFiles/damascene.dir/build
.PHONY : damascene/fast

stencilMatrixMultiply/Stencil.o: stencilMatrixMultiply/Stencil.cpp.o
.PHONY : stencilMatrixMultiply/Stencil.o

# target to build an object file
stencilMatrixMultiply/Stencil.cpp.o:
	$(MAKE) -f CMakeFiles/damascene.dir/build.make CMakeFiles/damascene.dir/stencilMatrixMultiply/Stencil.cpp.o
.PHONY : stencilMatrixMultiply/Stencil.cpp.o

stencilMatrixMultiply/Stencil.i: stencilMatrixMultiply/Stencil.cpp.i
.PHONY : stencilMatrixMultiply/Stencil.i

# target to preprocess a source file
stencilMatrixMultiply/Stencil.cpp.i:
	$(MAKE) -f CMakeFiles/damascene.dir/build.make CMakeFiles/damascene.dir/stencilMatrixMultiply/Stencil.cpp.i
.PHONY : stencilMatrixMultiply/Stencil.cpp.i

stencilMatrixMultiply/Stencil.s: stencilMatrixMultiply/Stencil.cpp.s
.PHONY : stencilMatrixMultiply/Stencil.s

# target to generate assembly for a file
stencilMatrixMultiply/Stencil.cpp.s:
	$(MAKE) -f CMakeFiles/damascene.dir/build.make CMakeFiles/damascene.dir/stencilMatrixMultiply/Stencil.cpp.s
.PHONY : stencilMatrixMultiply/Stencil.cpp.s

textons/filters.o: textons/filters.cpp.o
.PHONY : textons/filters.o

# target to build an object file
textons/filters.cpp.o:
	$(MAKE) -f CMakeFiles/damascene.dir/build.make CMakeFiles/damascene.dir/textons/filters.cpp.o
.PHONY : textons/filters.cpp.o

textons/filters.i: textons/filters.cpp.i
.PHONY : textons/filters.i

# target to preprocess a source file
textons/filters.cpp.i:
	$(MAKE) -f CMakeFiles/damascene.dir/build.make CMakeFiles/damascene.dir/textons/filters.cpp.i
.PHONY : textons/filters.cpp.i

textons/filters.s: textons/filters.cpp.s
.PHONY : textons/filters.s

# target to generate assembly for a file
textons/filters.cpp.s:
	$(MAKE) -f CMakeFiles/damascene.dir/build.make CMakeFiles/damascene.dir/textons/filters.cpp.s
.PHONY : textons/filters.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... damascene"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... stencilMatrixMultiply/Stencil.o"
	@echo "... stencilMatrixMultiply/Stencil.i"
	@echo "... stencilMatrixMultiply/Stencil.s"
	@echo "... textons/filters.o"
	@echo "... textons/filters.i"
	@echo "... textons/filters.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

